// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.hbsoo.grpc.api;

public final class RPCDateServiceApi {
  private RPCDateServiceApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RPCDateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hbsoo.grpc.api.RPCDateRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string userName = 1;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>optional string userName = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();
  }
  /**
   * <pre>
   * 定义请求体
   * </pre>
   *
   * Protobuf type {@code com.hbsoo.grpc.api.RPCDateRequest}
   */
  public  static final class RPCDateRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hbsoo.grpc.api.RPCDateRequest)
      RPCDateRequestOrBuilder {
    // Use RPCDateRequest.newBuilder() to construct.
    private RPCDateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RPCDateRequest() {
      userName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RPCDateRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hbsoo.grpc.api.RPCDateServiceApi.internal_static_com_hbsoo_grpc_api_RPCDateRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hbsoo.grpc.api.RPCDateServiceApi.internal_static_com_hbsoo_grpc_api_RPCDateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest.class, com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest.Builder.class);
    }

    public static final int USERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object userName_;
    /**
     * <code>optional string userName = 1;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userName_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userName_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest)) {
        return super.equals(obj);
      }
      com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest other = (com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest) obj;

      boolean result = true;
      result = result && getUserName()
          .equals(other.getUserName());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 定义请求体
     * </pre>
     *
     * Protobuf type {@code com.hbsoo.grpc.api.RPCDateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hbsoo.grpc.api.RPCDateRequest)
        com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hbsoo.grpc.api.RPCDateServiceApi.internal_static_com_hbsoo_grpc_api_RPCDateRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hbsoo.grpc.api.RPCDateServiceApi.internal_static_com_hbsoo_grpc_api_RPCDateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest.class, com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest.Builder.class);
      }

      // Construct using com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hbsoo.grpc.api.RPCDateServiceApi.internal_static_com_hbsoo_grpc_api_RPCDateRequest_descriptor;
      }

      public com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest getDefaultInstanceForType() {
        return com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest.getDefaultInstance();
      }

      public com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest build() {
        com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest buildPartial() {
        com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest result = new com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest(this);
        result.userName_ = userName_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest) {
          return mergeFrom((com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest other) {
        if (other == com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest.getDefaultInstance()) return this;
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>optional string userName = 1;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userName = 1;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userName = 1;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userName = 1;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.hbsoo.grpc.api.RPCDateRequest)
    }

    // @@protoc_insertion_point(class_scope:com.hbsoo.grpc.api.RPCDateRequest)
    private static final com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest();
    }

    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RPCDateRequest>
        PARSER = new com.google.protobuf.AbstractParser<RPCDateRequest>() {
      public RPCDateRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RPCDateRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RPCDateRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RPCDateRequest> getParserForType() {
      return PARSER;
    }

    public com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RPCDateResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hbsoo.grpc.api.RPCDateResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string serverDate = 1;</code>
     */
    java.lang.String getServerDate();
    /**
     * <code>optional string serverDate = 1;</code>
     */
    com.google.protobuf.ByteString
        getServerDateBytes();
  }
  /**
   * <pre>
   * 定义相应内容
   * </pre>
   *
   * Protobuf type {@code com.hbsoo.grpc.api.RPCDateResponse}
   */
  public  static final class RPCDateResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hbsoo.grpc.api.RPCDateResponse)
      RPCDateResponseOrBuilder {
    // Use RPCDateResponse.newBuilder() to construct.
    private RPCDateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RPCDateResponse() {
      serverDate_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RPCDateResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              serverDate_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hbsoo.grpc.api.RPCDateServiceApi.internal_static_com_hbsoo_grpc_api_RPCDateResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hbsoo.grpc.api.RPCDateServiceApi.internal_static_com_hbsoo_grpc_api_RPCDateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse.class, com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse.Builder.class);
    }

    public static final int SERVERDATE_FIELD_NUMBER = 1;
    private volatile java.lang.Object serverDate_;
    /**
     * <code>optional string serverDate = 1;</code>
     */
    public java.lang.String getServerDate() {
      java.lang.Object ref = serverDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverDate_ = s;
        return s;
      }
    }
    /**
     * <code>optional string serverDate = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServerDateBytes() {
      java.lang.Object ref = serverDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getServerDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serverDate_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getServerDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serverDate_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse)) {
        return super.equals(obj);
      }
      com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse other = (com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse) obj;

      boolean result = true;
      result = result && getServerDate()
          .equals(other.getServerDate());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SERVERDATE_FIELD_NUMBER;
      hash = (53 * hash) + getServerDate().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 定义相应内容
     * </pre>
     *
     * Protobuf type {@code com.hbsoo.grpc.api.RPCDateResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hbsoo.grpc.api.RPCDateResponse)
        com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hbsoo.grpc.api.RPCDateServiceApi.internal_static_com_hbsoo_grpc_api_RPCDateResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hbsoo.grpc.api.RPCDateServiceApi.internal_static_com_hbsoo_grpc_api_RPCDateResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse.class, com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse.Builder.class);
      }

      // Construct using com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serverDate_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hbsoo.grpc.api.RPCDateServiceApi.internal_static_com_hbsoo_grpc_api_RPCDateResponse_descriptor;
      }

      public com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse getDefaultInstanceForType() {
        return com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse.getDefaultInstance();
      }

      public com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse build() {
        com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse buildPartial() {
        com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse result = new com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse(this);
        result.serverDate_ = serverDate_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse) {
          return mergeFrom((com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse other) {
        if (other == com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse.getDefaultInstance()) return this;
        if (!other.getServerDate().isEmpty()) {
          serverDate_ = other.serverDate_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object serverDate_ = "";
      /**
       * <code>optional string serverDate = 1;</code>
       */
      public java.lang.String getServerDate() {
        java.lang.Object ref = serverDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serverDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string serverDate = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServerDateBytes() {
        java.lang.Object ref = serverDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serverDate = 1;</code>
       */
      public Builder setServerDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serverDate = 1;</code>
       */
      public Builder clearServerDate() {
        
        serverDate_ = getDefaultInstance().getServerDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serverDate = 1;</code>
       */
      public Builder setServerDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverDate_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.hbsoo.grpc.api.RPCDateResponse)
    }

    // @@protoc_insertion_point(class_scope:com.hbsoo.grpc.api.RPCDateResponse)
    private static final com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse();
    }

    public static com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RPCDateResponse>
        PARSER = new com.google.protobuf.AbstractParser<RPCDateResponse>() {
      public RPCDateResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RPCDateResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RPCDateResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RPCDateResponse> getParserForType() {
      return PARSER;
    }

    public com.hbsoo.grpc.api.RPCDateServiceApi.RPCDateResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hbsoo_grpc_api_RPCDateRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hbsoo_grpc_api_RPCDateRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hbsoo_grpc_api_RPCDateResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hbsoo_grpc_api_RPCDateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\022com.hbsoo.grpc.api\"\"\n\016RPCD" +
      "ateRequest\022\020\n\010userName\030\001 \001(\t\"%\n\017RPCDateR" +
      "esponse\022\022\n\nserverDate\030\001 \001(\t2f\n\016RPCDateSe" +
      "rvice\022T\n\007getDate\022\".com.hbsoo.grpc.api.RP" +
      "CDateRequest\032#.com.hbsoo.grpc.api.RPCDat" +
      "eResponse\"\000B\'\n\022com.hbsoo.grpc.apiB\021RPCDa" +
      "teServiceApib\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_hbsoo_grpc_api_RPCDateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hbsoo_grpc_api_RPCDateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hbsoo_grpc_api_RPCDateRequest_descriptor,
        new java.lang.String[] { "UserName", });
    internal_static_com_hbsoo_grpc_api_RPCDateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hbsoo_grpc_api_RPCDateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hbsoo_grpc_api_RPCDateResponse_descriptor,
        new java.lang.String[] { "ServerDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
